language: cpp
dist: trusty

git:
  submodules: true

# This reportedly works around an issue downloading packages from pypi on
# travis.  Consider removing this after the underlying issue is fixed.
# https://github.com/travis-ci/travis-ci/issues/2389
sudo: false

matrix:
    include:
    - os: linux
      env: PYTHON=3.6

before_install:
    - |
      if [ "$TRAVIS_OS_NAME" = "linux" ]; then export CXX=g++-4.8 CC=gcc-4.8; fi
      if [ -n "$PYTHON" ]; then
        if [ "$TRAVIS_OS_NAME" = "osx" ] && [ "${PYTHON:0:1}" = "3" ]; then
          brew update; brew install python3;
        fi
        pyenv global system $PYTHON
        pip install --user --upgrade pip virtualenv
        virtualenv -p python$PYTHON venv
        source venv/bin/activate
        pip install -U setuptools pip wheel
        pip install codecov
      fi

install:
    - python setup.py sdist
    - pip install --verbose dist/*.tar.gz

script:
    - coverage run setup.py test

after_success:
    - codecov